/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AreaChart {
    'data': string;
    'endcolor': string;
    'endopacity': string;
    'height': string;
    'marginbottom': string;
    'marginleft': string;
    'marginright': string;
    'margintop': string;
    'showaxes': string;
    'startcolor': string;
    'startopacity': string;
    'width': string;
    'xaxis': string;
    'yaxis': string;
  }
  interface GroupBarChart {
    'chartdata': any;
    'height': number;
    'marginbottom': string;
    'marginleft': string;
    'marginright': string;
    'margintop': string;
    'width': number;
  }
  interface LineChart {
    'connectnulls': number;
    'data': string;
    'data2': { key: string };
    'dotcolor': string;
    'enabledots': number;
    'formatter': any;
    'height': string;
    'marginbottom': string;
    'marginleft': string;
    'marginright': string;
    'margintop': string;
    'width': string;
    'xaxis': string;
    'yaxis': string;
  }
  interface MultiLineChart {
    'chartdata': any;
    'height': number;
    'marginbottom': string;
    'marginleft': string;
    'marginright': string;
    'margintop': string;
    'width': number;
  }
  interface ScatterPlot {
    'chartdata': any;
    'height': number;
    'marginbottom': string;
    'marginleft': string;
    'marginright': string;
    'margintop': string;
    'width': number;
  }
}

declare global {


  interface HTMLAreaChartElement extends Components.AreaChart, HTMLStencilElement {}
  var HTMLAreaChartElement: {
    prototype: HTMLAreaChartElement;
    new (): HTMLAreaChartElement;
  };

  interface HTMLGroupBarChartElement extends Components.GroupBarChart, HTMLStencilElement {}
  var HTMLGroupBarChartElement: {
    prototype: HTMLGroupBarChartElement;
    new (): HTMLGroupBarChartElement;
  };

  interface HTMLLineChartElement extends Components.LineChart, HTMLStencilElement {}
  var HTMLLineChartElement: {
    prototype: HTMLLineChartElement;
    new (): HTMLLineChartElement;
  };

  interface HTMLMultiLineChartElement extends Components.MultiLineChart, HTMLStencilElement {}
  var HTMLMultiLineChartElement: {
    prototype: HTMLMultiLineChartElement;
    new (): HTMLMultiLineChartElement;
  };

  interface HTMLScatterPlotElement extends Components.ScatterPlot, HTMLStencilElement {}
  var HTMLScatterPlotElement: {
    prototype: HTMLScatterPlotElement;
    new (): HTMLScatterPlotElement;
  };
  interface HTMLElementTagNameMap {
    'area-chart': HTMLAreaChartElement;
    'group-bar-chart': HTMLGroupBarChartElement;
    'line-chart': HTMLLineChartElement;
    'multi-line-chart': HTMLMultiLineChartElement;
    'scatter-plot': HTMLScatterPlotElement;
  }
}

declare namespace LocalJSX {
  interface AreaChart {
    'data'?: string;
    'endcolor'?: string;
    'endopacity'?: string;
    'height'?: string;
    'marginbottom'?: string;
    'marginleft'?: string;
    'marginright'?: string;
    'margintop'?: string;
    'showaxes'?: string;
    'startcolor'?: string;
    'startopacity'?: string;
    'width'?: string;
    'xaxis'?: string;
    'yaxis'?: string;
  }
  interface GroupBarChart {
    'chartdata'?: any;
    'height'?: number;
    'marginbottom'?: string;
    'marginleft'?: string;
    'marginright'?: string;
    'margintop'?: string;
    'width'?: number;
  }
  interface LineChart {
    'connectnulls'?: number;
    'data'?: string;
    'data2'?: { key: string };
    'dotcolor'?: string;
    'enabledots'?: number;
    'formatter'?: any;
    'height'?: string;
    'marginbottom'?: string;
    'marginleft'?: string;
    'marginright'?: string;
    'margintop'?: string;
    'width'?: string;
    'xaxis'?: string;
    'yaxis'?: string;
  }
  interface MultiLineChart {
    'chartdata'?: any;
    'height'?: number;
    'marginbottom'?: string;
    'marginleft'?: string;
    'marginright'?: string;
    'margintop'?: string;
    'width'?: number;
  }
  interface ScatterPlot {
    'chartdata'?: any;
    'height'?: number;
    'marginbottom'?: string;
    'marginleft'?: string;
    'marginright'?: string;
    'margintop'?: string;
    'width'?: number;
  }

  interface IntrinsicElements {
    'area-chart': AreaChart;
    'group-bar-chart': GroupBarChart;
    'line-chart': LineChart;
    'multi-line-chart': MultiLineChart;
    'scatter-plot': ScatterPlot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'area-chart': LocalJSX.AreaChart & JSXBase.HTMLAttributes<HTMLAreaChartElement>;
      'group-bar-chart': LocalJSX.GroupBarChart & JSXBase.HTMLAttributes<HTMLGroupBarChartElement>;
      'line-chart': LocalJSX.LineChart & JSXBase.HTMLAttributes<HTMLLineChartElement>;
      'multi-line-chart': LocalJSX.MultiLineChart & JSXBase.HTMLAttributes<HTMLMultiLineChartElement>;
      'scatter-plot': LocalJSX.ScatterPlot & JSXBase.HTMLAttributes<HTMLScatterPlotElement>;
    }
  }
}


