/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AreaChart {
    'data': string;
    'endcolor': string;
    'endopacity': string;
    'height': string;
    'marginbottom': string;
    'marginleft': string;
    'marginright': string;
    'margintop': string;
    'showaxes': string;
    'startcolor': string;
    'startopacity': string;
    'width': string;
    'xaxis': string;
    'yaxis': string;
  }
  interface LineChart {
    'connectnulls': number;
    'data': string;
    'data2': { key: string };
    'dotcolor': string;
    'enabledots': number;
    'formatter': any;
    'height': string;
    'marginbottom': string;
    'marginleft': string;
    'marginright': string;
    'margintop': string;
    'width': string;
    'xaxis': string;
    'yaxis': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAreaChartElement extends Components.AreaChart, HTMLStencilElement {}
  var HTMLAreaChartElement: {
    prototype: HTMLAreaChartElement;
    new (): HTMLAreaChartElement;
  };

  interface HTMLLineChartElement extends Components.LineChart, HTMLStencilElement {}
  var HTMLLineChartElement: {
    prototype: HTMLLineChartElement;
    new (): HTMLLineChartElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'area-chart': HTMLAreaChartElement;
    'line-chart': HTMLLineChartElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AreaChart {
    'data'?: string;
    'endcolor'?: string;
    'endopacity'?: string;
    'height'?: string;
    'marginbottom'?: string;
    'marginleft'?: string;
    'marginright'?: string;
    'margintop'?: string;
    'showaxes'?: string;
    'startcolor'?: string;
    'startopacity'?: string;
    'width'?: string;
    'xaxis'?: string;
    'yaxis'?: string;
  }
  interface LineChart {
    'connectnulls'?: number;
    'data'?: string;
    'data2'?: { key: string };
    'dotcolor'?: string;
    'enabledots'?: number;
    'formatter'?: any;
    'height'?: string;
    'marginbottom'?: string;
    'marginleft'?: string;
    'marginright'?: string;
    'margintop'?: string;
    'width'?: string;
    'xaxis'?: string;
    'yaxis'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'area-chart': AreaChart;
    'line-chart': LineChart;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'area-chart': LocalJSX.AreaChart & JSXBase.HTMLAttributes<HTMLAreaChartElement>;
      'line-chart': LocalJSX.LineChart & JSXBase.HTMLAttributes<HTMLLineChartElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


